### ISSUE TITLE
Heatmap not working after latest release

### ISSUE THREAD

**Issue by prateekraina** [sjkp/heatmap#10]
Hi Simon,

After latest release heatmap visual has stopped working for me.
I have attached my dataset and pbix file as well. If you use the latest version, it does not plot.
If i use version prior to latest release, it works fine.

Also, can you please explain how Auto Intensity works?

Kindly look into this.

Prateek Raina
[Dataset.zip](https://github.com/sjkp/heatmap/files/1571115/Dataset.zip)

**Comment by Ryan-Gao** [comment]
same issue for me

**Comment by aperrott** [comment]
I am using Heatmap for the first time, but it doesn't seem to work with the current PBI. I see the map, but nothing id displayed on it :-(

**Comment by fishboneox** [comment]
Same here. Any ideas yet how to solve it?

**Comment by prateekraina** [comment]
Hi Simon,

Kindly acknowledge if you could look into this. Many people are counting on you :)

Prateek Raina
