### ISSUE TITLE
Why is MaxWidth and MaxHeight 

### ISSUE THREAD

**Issue by niels9001** [sjkp/heatmap#2]
I'm trying to use the .pbiviz file, but in PowerBI I can't set the MaxWidth and MaxHeight. This basically results in the heatmap stopping at around 50% for me.

I can see in the source code that these parameters have been commented out. Any idea why this is?

**Comment by sjkp** [comment]
It reads it from the image size. So you should set an background image that have the dimension of your data, or alternatively scale your datapoints to fit your background image. I removed the settings to make it more user friend.

**Comment by niels9001** [comment]
I see.. Problem is, Power BI only support images that are not larger than 1280 pixels (it will not fit on the screen otherwise). Also, in my case I might have different image sizes (especially different resolutions for different phones). Using a percentage as X/Y coordinates and Width and Height as parameters would solve this I think.

**Comment by sjkp** [comment]
You can still use an image that any size e..g. 2000x2000 if you want, it is scaled to the size of the visual. The image should just align with your data.
