### ISSUE TITLE
Adding local images as background

### ISSUE THREAD

**Issue by DNSPK** [sjkp/heatmap#5]
Hi,
I am having difficulty on adding an image on the visual as background which is on the harddrive.
This is the value I am passing for background url.
file:///C:\Users\dnspk\pictures\test.png
Is there anything that I am missing? 
I also tried to input a publicly available url like  
https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwis_PXPkPjWAhVC4WMKHYEYAIIQjRwIBw&url=http%3A%2F%2Fwww.qygjxz.com%2Fpopular-images.html&psig=AOvVaw1EvAHCn_2tVeVRo0wPkt96&ust=1508345937383659

Even this does not work.
Any help would be greatly appreciated.
Thanks.

**Comment by sjkp** [comment]
Hi @DNSPK the visual doesn't support local urls. As that wouldn't work if you decided to publish your report to powerbi.com. 

In regards to the web image you tried, you need to link directly to the image. When you find images with google search be sure to right click the image and select "copy image address", typically it would end with .gif, .jpg or .png.
