### ISSUE TITLE
Dynamic Max Intensity option

### ISSUE THREAD

**Issue by prateekraina** [sjkp/heatmap#6]
Hi,

First of all a very great custom visual. Kudos!

I have a request. Can you kindly make Max Intensity option such that we can use a measure instead of hard coding that value. Please respond.

Prateek Raina

**Comment by sjkp** [comment]
Hi @prateekraina that should be doable. I will update later this week, stay turned.

**Comment by prateekraina** [comment]
Thanks @sjkp . Will look forward for your update.

**Comment by prateekraina** [comment]
Hi @sjkp . Eagerly waiting for this feature.

**Comment by sjkp** [comment]
It is implemented in version 4.0.0 let me know if it works are you intend.
