### ISSUE TITLE
Unable to find settings for Canvas size

### ISSUE THREAD

**Issue by MRBIGGE** [sjkp/heatmap#8]
Hi Simon.
I can not find the Canvas size settings that appear in your youtube video
https://www.youtube.com/watch?v=KNy0PQU3HTk
  
![image](https://user-images.githubusercontent.com/34238509/33571325-f93c6f4a-d92f-11e7-99e5-991fc1356d22.png)

**Comment by sjkp** [comment]
Hi @MRBIGGE 
That settings is not longer there in the newest versions. It auto detect the size of the image, thus you don't have to supply it yourself.

**Comment by MRBIGGE** [comment]
Thx!
It doesn’t work so well for me and my image.
I identify the it is comments out in the source.


Med vänlig hälsning, Birger Arvidsson

14 dec. 2017 kl. 11:34 skrev Simon J.K. Pedersen <notifications@github.com<mailto:notifications@github.com>>:


Hi @MRBIGGE<https://github.com/mrbigge>
That settings is not longer there in the newest versions. It auto detect the size of the image, thus you don't have to supply it yourself.

**Comment by sjkp** [comment]
Which image type are you using? Try converting it to png or jpeg.
